version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/notebooks/app
    command: ["python", "app/app.py"]
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll", "1"]
